# frozen_string_literal: true

source "https://rubygems.org"

gem 'roda'

#gem "falcon"
gem "puma"
#gem 'iodine'
#gem 'thin'
#gem "passenger", ">= 5.3.2", require: "phusion_passenger/rack_handler"

gem "passenger", ">= 5.3.2", require: "phusion_passenger/rack_handler"
gem 'sequel'
gem 'sqlite3'
gem 'zeitwerk'
gem 'html_slice'

group :development do
  gem 'guard-puma'
  #gem 'rerun'
  gem 'byebug'
  gem 'rspec'
end
