# frozen_string_literal: true

source "https://rubygems.org"

gem 'roda'
#gem 'thin', '~> 1.8', '>= 1.8.2'
gem "passenger", ">= 5.3.2", require: "phusion_passenger/rack_handler"
gem 'sequel'
gem 'sqlite3'
gem 'zeitwerk'
gem 'html_slice'

group :development do
  gem 'rerun'
  gem 'byebug'
  gem 'rspec'
end
