# frozen_string_literal: true

source "https://rubygems.org"

gem 'roda'
gem 'roda-i18n'

gem 'oj'
gem 'async'
gem 'sequel'
gem 'sqlite3'
#gem 'jdbc-sqlite3'
gem 'zeitwerk'
gem 'ostruct'

gem "puma"
#gem "falcon"
#gem 'iodine'
#gem 'thin'

group :development do
  gem 'guard-puma'
  #gem 'byebug'
  gem 'pry'
  gem 'rspec'
end
