# frozen_string_literal: true

source "https://rubygems.org"

# Base
gem "roda"
gem "roda-i18n"
gem "zeitwerk"

# Authentication
gem "rodauth"
gem "bcrypt"
gem "mail"

# Database
gem "sequel"
gem "pg"
#gem "sequel_pg"
# gem 'jdbc-sqlite3'

# Web Server
gem "puma"
# gem "falcon"
# gem 'iodine'
# gem 'thin'

# Performance
gem "oj"
# gem 'async'

# CLI
gem 'dry-cli'

# Misc
gem 'html_slice'
gem 'singleton'

group :development do
  gem "guard-puma"
  gem "debug"
  # gem "pry"
  gem "standard"
  gem "minitest"
  gem "minitest-hooks"
  gem "rack-test"
end
